# Generated by Django 4.2.13 on 2026-06-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_seed_ejes_ods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrizoperativa',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('cerrada', 'Cerrada')], db_index=True, default='borrador', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='periodoacademico',
            constraint=models.UniqueConstraint(fields=('anio', 'semestre'), name='unique_periodo_anio_semestre'),
        ),
    ]
