# Generated by Django 4.2.13 on 2026-06-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_anexo4_completo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronogramaaccion',
            name='estado_avance',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='proyectorsu',
            name='fuente_financiamiento',
            field=models.CharField(blank=True, choices=[('recursos_propios_unsa', 'Recursos Propios UNSA'), ('cooperacion_externa', 'Cooperación externa'), ('aporte_facultad', 'Aporte a la Facultad'), ('autofinanciado', 'Autofinanciado')], help_text='IX Fuente de financiamiento', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proyectorsu',
            name='tipo_actividad',
            field=models.JSONField(blank=True, default=list, help_text="1.11 Tipos de actividad seleccionados (lista, p.ej. ['asesoria','otro'])"),
        ),
        migrations.AlterField(
            model_name='proyectorsu',
            name='tipo_actividad_otro',
            field=models.CharField(blank=True, help_text="1.11 Descripción si se seleccionó 'Otro' como tipo de actividad", max_length=300, null=True),
        ),
    ]
