# Generated by Django 4.2.13 on 2026-06-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0004_remove_beneficiary_details_add_sustento_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectorsu',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En Revisión'), ('observado', 'Observado'), ('corregido', 'Corregido'), ('aprobado', 'Aprobado'), ('en_ejecucion', 'En Ejecución'), ('finalizado', 'Finalizado'), ('rechazado', 'Rechazado')], db_index=True, default='borrador', max_length=30),
        ),
    ]
