# Generated by Django 4.2.13 on 2026-06-20 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_alter_proyectorsu_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidaPresupuestaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(help_text='Descripción del rubro o concepto de gasto', max_length=300)),
                ('unidad', models.CharField(blank=True, help_text='Unidad de medida (ej: unidad, hora, taller, kit)', max_length=50)),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Número de unidades')),
                ('costo_unitario', models.DecimalField(decimal_places=2, help_text='Costo por unidad en Soles (S/)', max_digits=10)),
                ('fuente', models.CharField(blank=True, choices=[('recursos_propios_unsa', 'Recursos Propios UNSA'), ('cooperacion_externa', 'Cooperación externa'), ('aporte_facultad', 'Aporte a la Facultad'), ('autofinanciado', 'Autofinanciado')], help_text='Fuente de financiamiento de este rubro', max_length=50, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_presupuesto', to='proyectos.proyectorsu')),
            ],
            options={
                'verbose_name': 'Partida Presupuestaria',
                'verbose_name_plural': 'Partidas Presupuestarias',
                'db_table': 'proyecto_partidas_presupuesto',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='MetaIndicadorProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_descripcion', models.CharField(help_text='Descripción de la meta (ej: Capacitar a 50 docentes en reciclaje)', max_length=400)),
                ('indicador_nombre', models.CharField(help_text='Nombre del indicador de medición (ej: Nro. de docentes capacitados)', max_length=300)),
                ('unidad_medida', models.CharField(blank=True, help_text='Unidad de medida del indicador (ej: personas, %, talleres)', max_length=100)),
                ('linea_base', models.DecimalField(blank=True, decimal_places=2, help_text='Valor inicial antes de la intervención (situación de partida)', max_digits=10, null=True)),
                ('valor_meta', models.DecimalField(blank=True, decimal_places=2, help_text='Valor objetivo a alcanzar al finalizar el proyecto', max_digits=10, null=True)),
                ('valor_alcanzado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor efectivamente alcanzado — se registra durante/al cierre del proyecto', max_digits=10, null=True)),
                ('metodo_verificacion', models.TextField(blank=True, help_text='Cómo se verifica el cumplimiento (ej: Lista de asistencia, Encuesta)')),
                ('fuente_verificacion', models.CharField(blank=True, help_text='Documento o fuente del dato de verificación', max_length=300)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_indicadores', to='proyectos.proyectorsu')),
            ],
            options={
                'verbose_name': 'Meta e Indicador',
                'verbose_name_plural': 'Metas e Indicadores',
                'db_table': 'proyecto_metas_indicadores',
                'ordering': ['orden'],
            },
        ),
    ]
