# Generated by Django 4.2.13 on 2026-06-20 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0006_add_partida_presupuestaria_and_meta_indicador'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaseProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada')], default='pendiente', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='proyectos.proyectorsu')),
            ],
            options={
                'verbose_name': 'Fase de Proyecto',
                'verbose_name_plural': 'Fases de Proyecto',
                'db_table': 'fases_proyecto',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TareaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado')], default='pendiente', max_length=30)),
                ('porcentaje_avance', models.PositiveIntegerField(default=0)),
                ('lugar_ejecucion', models.CharField(blank=True, max_length=300, null=True)),
                ('tipo_actividad', models.CharField(blank=True, choices=[('programas_formativos', 'Programas formativos'), ('acompanamiento_social', 'Acompañamiento social'), ('asesorias', 'Asesorías'), ('actividades_comunitarias', 'Actividades comunitarias'), ('otras', 'Otras')], max_length=150, null=True)),
                ('aplica_encuesta', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='proyectos.faseproyecto')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarea de Proyecto',
                'verbose_name_plural': 'Tareas de Proyecto',
                'db_table': 'tareas_proyecto',
                'ordering': ['fecha_fin', 'id'],
            },
        ),
        migrations.RemoveField(
            model_name='cronogramaaccion',
            name='proyecto',
        ),
        migrations.RenameField(
            model_name='partidapresupuestaria',
            old_name='concepto',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='partidapresupuestaria',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Descripción del rubro o concepto de gasto', max_length=500),
        ),
        migrations.AddField(
            model_name='partidapresupuestaria',
            name='categoria',
            field=models.CharField(blank=True, choices=[('movilidad', 'Movilidad'), ('material_educativo', 'Material educativo'), ('equipos', 'Equipos'), ('alimentacion', 'Alimentación'), ('servicios', 'Servicios'), ('otros', 'Otros')], help_text='Categoría del gasto', max_length=150),
        ),
        migrations.AddField(
            model_name='partidapresupuestaria',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='partidapresupuestaria',
            name='monto_ejecutado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto efectivamente gastado al cierre', max_digits=10),
        ),
        migrations.AddField(
            model_name='partidapresupuestaria',
            name='tipo_recurso',
            field=models.CharField(blank=True, choices=[('humano', 'Humano'), ('material', 'Material'), ('financiero', 'Financiero')], help_text='Tipo de recurso', max_length=50),
        ),
        migrations.AddField(
            model_name='partidapresupuestaria',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='partidapresupuestaria',
            table='presupuesto_proyecto',
        ),
        migrations.DeleteModel(
            name='ActividadProyecto',
        ),
        migrations.DeleteModel(
            name='CronogramaAccion',
        ),
    ]
