# Generated by Django 4.2.13 on 2026-06-21 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0007_fase_tarea_presupuesto_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la actividad', max_length=300)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve', null=True)),
                ('curso_vinculado', models.CharField(blank=True, help_text='Asignatura vinculada', max_length=300, null=True)),
                ('responsable', models.CharField(blank=True, help_text='Responsable de la actividad', max_length=200, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('evidencia_esperada', models.CharField(blank=True, help_text='Evidencia esperada (ej: Fotos, listas, informes)', max_length=400, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Actividad de Proyecto',
                'verbose_name_plural': 'Actividades de Proyecto',
                'db_table': 'proyecto_actividades',
                'ordering': ['orden', 'fecha'],
            },
        ),
        migrations.CreateModel(
            name='CronogramaAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción de la acción', max_length=400)),
                ('mes_semana', models.CharField(blank=True, help_text='Periodo de ejecución (ej: Mes 1, Sem 2)', max_length=100, null=True)),
                ('responsable', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_avance', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado')], default='pendiente', max_length=30)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Acción de Cronograma',
                'verbose_name_plural': 'Acciones de Cronograma',
                'db_table': 'proyecto_cronograma',
                'ordering': ['orden'],
            },
        ),
        migrations.RemoveField(
            model_name='objetivoespecifico',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='tareaproyecto',
            name='fase',
        ),
        migrations.RemoveField(
            model_name='tareaproyecto',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='proyectorsu',
            name='objetivo_general',
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='obj_logro_intervencion',
            field=models.TextField(blank=True, help_text='IV ¿Qué queremos lograr con nuestra intervención en el grupo beneficiario?', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='obj_mejora_curricular',
            field=models.TextField(blank=True, help_text='IV ¿Qué queremos mejorar en el proceso curricular?', null=True),
        ),
        migrations.AlterField(
            model_name='proyectorsu',
            name='lugar_ejecucion',
            field=models.TextField(blank=True, help_text='1.18 Lugar de ejecución (ej: Distrito de Cayma, Arequipa)', null=True),
        ),
        migrations.DeleteModel(
            name='FaseProyecto',
        ),
        migrations.DeleteModel(
            name='ObjetivoEspecifico',
        ),
        migrations.DeleteModel(
            name='TareaProyecto',
        ),
        migrations.AddField(
            model_name='cronogramaaccion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma', to='proyectos.proyectorsu'),
        ),
        migrations.AddField(
            model_name='actividadproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='proyectos.proyectorsu'),
        ),
    ]
