# Generated by Django 4.2.13 on 2026-06-27 02:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0004_update_ejes_rsu'),
        ('proyectos', '0014_rename_eje_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectorsu',
            name='eje_detalle',
            field=models.TextField(blank=True, help_text="1.10 Descripción obligatoria cuando el eje RSU seleccionado es 'Otros'", null=True),
        ),
        migrations.AlterField(
            model_name='proyectorsu',
            name='eje_rsu',
            field=models.ForeignKey(help_text='1.10 Eje RSU principal del proyecto (selección excluyente)', on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='planificacion.ejersu'),
        ),
        migrations.AlterField(
            model_name='proyectorsu',
            name='eje_rsu_subitems',
            field=models.JSONField(blank=True, default=dict, help_text='1.10 Sub-ítems seleccionados por eje RSU (Gestión, Formación, Investigación, Extensión)'),
        ),
        migrations.CreateModel(
            name='FuenteFinanciamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(choices=[('recursos_propios_unsa', 'Recursos Propios UNSA'), ('cooperacion_externa', 'Cooperación externa'), ('aporte_facultad', 'Aporte a la Facultad'), ('autofinanciado', 'Autofinanciado')], help_text='Fuente de financiamiento', max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, default=0, help_text='Monto aportado por esta fuente (S/)', max_digits=12)),
                ('descripcion', models.CharField(blank=True, help_text='Detalle adicional sobre esta fuente', max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuentes_financiamiento', to='proyectos.proyectorsu')),
            ],
            options={
                'verbose_name': 'Fuente de Financiamiento',
                'verbose_name_plural': 'Fuentes de Financiamiento',
                'db_table': 'fuente_financiamiento_proyecto',
            },
        ),
    ]
