# Generated by Django 4.2.13 on 2026-06-27 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0015_fuente_financiamiento_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidapresupuestaria',
            name='fuente',
            field=models.ForeignKey(blank=True, help_text='Fuente de financiamiento de este rubro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas', to='proyectos.fuentefinanciamiento'),
        ),
    ]
