# Generated by Django 4.2.13 on 2026-06-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0018_ejes_subitems_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipobeneficiario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
