# Generated by Django 4.2.13 on 2026-07-03 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0020_cronograma_fecha_inicio_fin'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='proyectorsu',
            name='unique_proyecto_escuela_periodo_anio',
        ),
    ]
