# Generated by Django 4.2.13 on 2026-07-04 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0021_remove_proyectorsu_unique_proyecto_escuela_periodo_anio'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('aprobado', 'Aprobado'), ('observado', 'Observado')], help_text='Resultado del dictamen: aprobado | observado', max_length=20)),
                ('comentario_tecnico', models.TextField(blank=True, default='', help_text='Obligatorio cuando la decisión es "observado". Describe las correcciones requeridas.')),
                ('estado_anterior', models.CharField(help_text='Snapshot del estado del proyecto antes del dictamen', max_length=30)),
                ('estado_nuevo', models.CharField(help_text='Estado asignado al proyecto por este dictamen', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Fecha y hora exacta del dictamen — inmutable')),
                ('proyecto', models.ForeignKey(help_text='Proyecto evaluado', on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='proyectos.proyectorsu')),
                ('revisor', models.ForeignKey(help_text='Usuario con rol Departamento que emite el dictamen', on_delete=django.db.models.deletion.PROTECT, related_name='revisiones_emitidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revisión de Proyecto',
                'verbose_name_plural': 'Revisiones de Proyectos',
                'db_table': 'revision_proyecto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aprobacion', 'Aprobación'), ('observacion', 'Observación'), ('envio_revision', 'Enviado a Revisión'), ('correccion', 'Corrección Enviada')], help_text='Tipo de evento que originó la notificación', max_length=50)),
                ('titulo', models.CharField(help_text='Título breve de la notificación', max_length=300)),
                ('mensaje', models.TextField(help_text='Detalle completo: resultado, evaluador, fecha, comentario técnico si aplica')),
                ('leida', models.BooleanField(default=False, help_text='Si el destinatario ya leyó la notificación')),
                ('leida_en', models.DateTimeField(blank=True, help_text='Timestamp cuando fue marcada como leída', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('destinatario', models.ForeignKey(help_text='Usuario que recibe la notificación (docente responsable)', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(blank=True, help_text='Proyecto al que hace referencia la notificación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='proyectos.proyectorsu')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, default='', help_text='Estado previo del proyecto', max_length=30)),
                ('estado_nuevo', models.CharField(help_text='Nuevo estado asignado', max_length=30)),
                ('comentario', models.TextField(blank=True, default='', help_text='Motivo del cambio, observación técnica, etc.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP del cliente que realizó la acción', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp inmutable del cambio de estado')),
                ('proyecto', models.ForeignKey(help_text='Proyecto cuyo estado cambió', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='proyectos.proyectorsu')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó el cambio de estado', on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado_proyecto', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Estado de Proyecto',
                'verbose_name_plural': 'Historial de Estados de Proyectos',
                'db_table': 'historial_estado_proyecto',
                'ordering': ['-created_at'],
            },
        ),
    ]
