# Generated by Django 4.2.13 on 2026-07-09 19:21

import apps.proyectos.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0022_revisionproyecto_notificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosustentoproyecto',
            name='archivo',
            field=models.FileField(upload_to='proyectos/sustento/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx']), apps.proyectos.models.validate_documento_sustento_size]),
        ),
    ]
