# Generated by Django 4.2.13 on 2026-07-16 20:53

import apps.proyectos.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0023_alter_documentosustentoproyecto_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Descripción del avance realizado.')),
                ('estado_actividad', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ejecucion', 'En Ejecución'), ('completada', 'Completada')], help_text='Estado que se fija a la actividad con este avance.', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones del docente (opcional).', null=True)),
                ('estado_revision', models.CharField(choices=[('registrado', 'Registrado'), ('observado', 'Observado'), ('corregido', 'Corregido')], db_index=True, default='registrado', max_length=20)),
                ('comentario_revision', models.TextField(blank=True, help_text='Comentario del revisor al observar el avance.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revisado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Avance de Actividad',
                'verbose_name_plural': 'Avances de Actividad',
                'db_table': 'proyecto_avances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='actividadproyecto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ejecucion', 'En Ejecución'), ('completada', 'Completada')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='porcentaje_ejecucion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% de ejecución (0-100) calculado automáticamente según el estado de las actividades.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('aprobacion', 'Aprobación'), ('observacion', 'Observación'), ('envio_revision', 'Enviado a Revisión'), ('correccion', 'Corrección Enviada'), ('avance_observado', 'Avance Observado'), ('avance_corregido', 'Avance Corregido')], help_text='Tipo de evento que originó la notificación', max_length=50),
        ),
        migrations.CreateModel(
            name='EvidenciaAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('archivo', 'Archivo'), ('enlace', 'Enlace Drive')], max_length=10)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='proyectos/evidencias/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), apps.proyectos.models.validate_evidencia_size])),
                ('enlace_drive', models.URLField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('eliminada', models.BooleanField(db_index=True, default=False)),
                ('eliminada_en', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('avance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='proyectos.avanceactividad')),
            ],
            options={
                'verbose_name': 'Evidencia de Avance',
                'verbose_name_plural': 'Evidencias de Avance',
                'db_table': 'proyecto_evidencias',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='avanceactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='proyectos.actividadproyecto'),
        ),
        migrations.AddField(
            model_name='avanceactividad',
            name='autor',
            field=models.ForeignKey(help_text='Docente responsable que registró el avance.', on_delete=django.db.models.deletion.PROTECT, related_name='avances_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avanceactividad',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to='proyectos.proyectorsu'),
        ),
        migrations.AddField(
            model_name='avanceactividad',
            name='revisor',
            field=models.ForeignKey(blank=True, help_text='Usuario que observó el avance (Jefatura RSU/Departamento/Admin).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avances_revisados', to=settings.AUTH_USER_MODEL),
        ),
    ]
