# Generated by Django 4.2.13 on 2026-07-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0024_hu05_avances_evidencias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectorsu',
            name='indicador',
        ),
        migrations.RemoveField(
            model_name='proyectorsu',
            name='meta_cuantitativa',
        ),
        migrations.AddField(
            model_name='actividadproyecto',
            name='archivo_evidencia',
            field=models.FileField(blank=True, help_text='Archivo de evidencia', null=True, upload_to='evidencias_actividades/'),
        ),
        migrations.AddField(
            model_name='actividadproyecto',
            name='url_evidencia',
            field=models.URLField(blank=True, help_text='URL de evidencia (Drive, etc.)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cronogramaaccion',
            name='estado_avance',
            field=models.CharField(choices=[('no_iniciado', 'No Iniciado'), ('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado')], default='no_iniciado', max_length=30),
        ),
    ]
