# Generated by Django 4.2.13 on 2026-07-19 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0006_seed_sub_ejes'),
        ('proyectos', '0025_remove_proyectorsu_indicador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectorsu',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='planificacion.periodoacademico'),
        ),
    ]
