# Generated by Django 4.2.13 on 2026-09-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0026_alter_proyectorsu_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoasignatura',
            name='nombre_asignatura',
            field=models.CharField(max_length=500),
        ),
    ]
