# Generated by Django 4.2.13 on 2026-09-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0008_objetivonacional_objetivoregional'),
        ('proyectos', '0027_alter_proyectoasignatura_nombre_asignatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectorsu',
            name='objetivos_nacionales',
            field=models.ManyToManyField(blank=True, db_table='proyecto_objetivos_nacionales', help_text='Objetivos Nacionales con los que se alinea el proyecto', related_name='proyectos', to='planificacion.objetivonacional'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='objetivos_regionales',
            field=models.ManyToManyField(blank=True, db_table='proyecto_objetivos_regionales', help_text='Objetivos Regionales con los que se alinea el proyecto', related_name='proyectos', to='planificacion.objetivoregional'),
        ),
    ]
