# Generated by Django 4.2.13 on 2026-09-12 22:32
"""
Convierte 'eje_rsu' (ForeignKey, un solo eje) en 'ejes_rsu' (ManyToMany,
selección múltiple).

Motivo: el formulario impedía marcar más de un eje RSU por proyecto, pero en
la práctica un proyecto puede alinearse con varios ejes a la vez (caso real
reportado: un proyecto presentado con dos ejes que el sistema anterior no
dejaba guardar).

Orden de las operaciones (importante para no perder datos):
1. Se agrega el campo 'ejes_rsu' (M2M) sin tocar el FK viejo todavía.
2. Se copia el valor de 'eje_rsu_id' de cada proyecto a 'ejes_rsu' (data
   migration).
3. Recién entonces se elimina el campo 'eje_rsu'.
"""
from django.db import migrations, models


def copiar_eje_rsu_a_ejes_rsu(apps, schema_editor):
    ProyectoRSU = apps.get_model('proyectos', 'ProyectoRSU')
    for proyecto in ProyectoRSU.objects.exclude(eje_rsu__isnull=True):
        proyecto.ejes_rsu.add(proyecto.eje_rsu_id)


def revertir_copia(apps, schema_editor):
    # No hace falta reconstruir el FK: RemoveField ya no existiría en el
    # estado previo y AddField(eje_rsu) de la migracion inversa lo deja en
    # null. No hay perdida adicional que revertir aqui.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0008_objetivonacional_objetivoregional'),
        ('proyectos', '0028_proyectorsu_objetivos_nacionales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectorsu',
            name='ejes_rsu',
            field=models.ManyToManyField(db_table='proyecto_ejes_rsu', help_text='1.10 Eje(s) RSU del proyecto (se permite más de uno)', related_name='proyectos', to='planificacion.ejersu'),
        ),
        migrations.RunPython(copiar_eje_rsu_a_ejes_rsu, revertir_copia),
        migrations.RemoveField(
            model_name='proyectorsu',
            name='eje_rsu',
        ),
    ]
