# Generated by Django 4.2.13 on 2026-09-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0029_remove_proyectorsu_eje_rsu_proyectorsu_ejes_rsu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('aprobacion', 'Aprobación'), ('observacion', 'Observación'), ('envio_revision', 'Enviado a Revisión'), ('correccion', 'Corrección Enviada'), ('avance_observado', 'Avance Observado'), ('avance_corregido', 'Avance Corregido'), ('finalizacion', 'Proyecto Finalizado'), ('listo_para_cerrar', 'Listo para Cerrar')], help_text='Tipo de evento que originó la notificación', max_length=50),
        ),
    ]
