# Generated by Django 4.2.13 on 2026-09-17 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0009_fix_ods_icono_url'),
        ('usuarios', '0014_fips_departamentos_y_escuelas'),
        ('proyectos', '0030_alter_notificacion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectorsu',
            name='departamento',
            field=models.ForeignKey(blank=True, help_text='1.3 Departamento Académico', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='usuarios.departamentoacademico'),
        ),
        migrations.AlterField(
            model_name='proyectorsu',
            name='ejes_rsu',
            field=models.ManyToManyField(blank=True, db_table='proyecto_ejes_rsu', help_text='1.10 Eje(s) RSU del proyecto (se permite más de uno)', related_name='proyectos', to='planificacion.ejersu'),
        ),
        migrations.AlterField(
            model_name='proyectorsu',
            name='escuela',
            field=models.ForeignKey(blank=True, help_text='1.2 Escuela Profesional', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='usuarios.escuelaprofesional'),
        ),
        migrations.AlterField(
            model_name='proyectorsu',
            name='ods',
            field=models.ManyToManyField(blank=True, db_table='proyecto_ods', related_name='proyectos', to='planificacion.ods'),
        ),
        migrations.AlterField(
            model_name='proyectorsu',
            name='semestre_academico',
            field=models.CharField(blank=True, default='', help_text='1.4 Semestre académico (ej: 2023-A)', max_length=20),
        ),
    ]
