# Generated by Django 4.2.13 on 2026-10-01 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0031_alter_proyectorsu_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronogramaaccion',
            name='actividad',
            field=models.ForeignKey(blank=True, help_text='Actividad (sección VI) a la que pertenece la acción', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='proyectos.actividadproyecto'),
        ),
        migrations.AddField(
            model_name='cronogramaaccion',
            name='evidencia_esperada',
            field=models.CharField(blank=True, default='', help_text='Evidencia esperada de la acción (ej: fotos, listas, informes)', max_length=400),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='docentes_participantes',
            field=models.JSONField(blank=True, default=list, help_text='1.7 Nombres de los docentes que participan (uno por elemento)'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='observacion_estudiantes',
            field=models.TextField(blank=True, default='', help_text='1.8 Observación sobre los estudiantes participantes'),
        ),
        migrations.AddField(
            model_name='revisionproyecto',
            name='etapa',
            field=models.CharField(choices=[('planificacion', 'Planificación'), ('finalizacion', 'Finalización')], db_index=True, default='planificacion', help_text='Qué se evaluó: la planificación o el informe de finalización', max_length=20),
        ),
        migrations.AddField(
            model_name='revisionproyecto',
            name='observaciones_secciones',
            field=models.JSONField(blank=True, default=dict, help_text='Observaciones por sección del formulario {clave_seccion: texto}'),
        ),
        migrations.AlterField(
            model_name='evidenciaavance',
            name='enlace_drive',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('aprobacion', 'Aprobación'), ('observacion', 'Observación'), ('envio_revision', 'Enviado a Revisión'), ('correccion', 'Corrección Enviada'), ('avance_observado', 'Avance Observado'), ('avance_corregido', 'Avance Corregido'), ('finalizacion', 'Proyecto Finalizado'), ('listo_para_cerrar', 'Listo para Cerrar'), ('informe_finalizacion_enviado', 'Informe de Finalización Enviado'), ('informe_finalizacion_observado', 'Informe de Finalización Observado'), ('constancia_disponible', 'Constancia de Finalización Disponible')], help_text='Tipo de evento que originó la notificación', max_length=50),
        ),
        migrations.CreateModel(
            name='InformeFinalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado a revisión'), ('observado', 'Observado'), ('aprobado', 'Aprobado')], db_index=True, default='borrador', max_length=20)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('constancia_aprobada', models.BooleanField(default=False)),
                ('constancia_aprobada_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('constancia_aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constancias_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='informe_finalizacion', to='proyectos.proyectorsu')),
            ],
            options={
                'verbose_name': 'Informe de Finalización',
                'verbose_name_plural': 'Informes de Finalización',
                'db_table': 'informe_finalizacion',
            },
        ),
    ]
