# Generated by Django 4.2.13 on 2026-10-01 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0033_mover_datos_de_actividades'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividadproyecto',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Actividad de Proyecto', 'verbose_name_plural': 'Actividades de Proyecto'},
        ),
        migrations.RemoveField(
            model_name='actividadproyecto',
            name='archivo_evidencia',
        ),
        migrations.RemoveField(
            model_name='actividadproyecto',
            name='evidencia_esperada',
        ),
        migrations.RemoveField(
            model_name='actividadproyecto',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='actividadproyecto',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='actividadproyecto',
            name='url_evidencia',
        ),
    ]
