# Generated by Django 4.2.13 on 2026-07-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_restore_roles_minuta'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el usuario puede hacer login'),
        ),
    ]
