# Generated by Django 4.2.13 on 2026-07-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_usuario_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Docente', 'Docente'), ('Departamento', 'Departamento'), ('Jefatura RSU', 'Jefatura RSU')], max_length=50, unique=True),
        ),
    ]
