# Generated by Django 4.2.13 on 2026-06-15 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planificacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_sesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoRSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('titulo', models.CharField(max_length=400)),
                ('descripcion_general', models.TextField(blank=True, null=True)),
                ('fundamentacion', models.TextField(blank=True, null=True)),
                ('diagnostico_situacional', models.TextField(blank=True, null=True)),
                ('semestre_academico', models.CharField(max_length=20)),
                ('anio_carrera', models.IntegerField(blank=True, choices=[(1, '1.er año'), (2, '2.do año'), (3, '3.er año'), (4, '4.to año'), (5, '5.to año')], null=True)),
                ('es_tesis_quinto_anio', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_revision', 'En Revisión'), ('observado', 'Observado'), ('corregido', 'Corregido'), ('aprobado', 'Aprobado'), ('en_ejecucion', 'En Ejecución'), ('finalizado', 'Finalizado'), ('rechazado', 'Rechazado')], default='borrador', max_length=30)),
                ('presentado_con_anticipacion', models.BooleanField(default=False)),
                ('conclusiones', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('lecciones_aprendidas', models.TextField(blank=True, null=True)),
                ('medio_difusion', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_envio_revision', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='usuarios.departamentoacademico')),
                ('docente_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_responsable', to=settings.AUTH_USER_MODEL)),
                ('eje_rsu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='planificacion.ejersu')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='usuarios.escuelaprofesional')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='usuarios.facultad')),
                ('linea_estrategica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='planificacion.lineaestrategica')),
                ('objetivo_institucional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos', to='planificacion.objetivoinstitucional')),
                ('ods', models.ManyToManyField(db_table='proyecto_ods', related_name='proyectos', to='planificacion.ods')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='planificacion.periodoacademico')),
            ],
            options={
                'verbose_name': 'Proyecto RSU',
                'verbose_name_plural': 'Proyectos RSU',
                'db_table': 'proyectos_rsu',
            },
        ),
        migrations.CreateModel(
            name='ProyectoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_en_proyecto', models.CharField(choices=[('Colaborador', 'Colaborador'), ('Asesor', 'Asesor')], max_length=100)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos_participante', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes_adicionales', to='proyectos.proyectorsu')),
            ],
            options={
                'verbose_name': 'Docente de Proyecto',
                'verbose_name_plural': 'Docentes de Proyecto',
                'db_table': 'proyecto_docentes',
            },
        ),
        migrations.CreateModel(
            name='ProyectoAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asignatura', models.CharField(max_length=200)),
                ('codigo_asignatura', models.CharField(blank=True, max_length=50, null=True)),
                ('anio_carrera', models.IntegerField(blank=True, null=True)),
                ('semestre', models.CharField(blank=True, max_length=10, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='proyectos.proyectorsu')),
            ],
            options={
                'verbose_name': 'Asignatura de Proyecto',
                'verbose_name_plural': 'Asignaturas de Proyecto',
                'db_table': 'proyecto_asignaturas',
            },
        ),
    ]
