# Generated by Django 4.2.13 on 2026-06-18 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_seed_ejes_ods'),
        ('usuarios', '0003_seed_roles'),
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyectorsu',
            options={'ordering': ['-created_at'], 'verbose_name': 'Proyecto RSU', 'verbose_name_plural': 'Proyectos RSU'},
        ),
        migrations.RemoveField(
            model_name='proyectorsu',
            name='descripcion_general',
        ),
        migrations.RemoveField(
            model_name='proyectorsu',
            name='diagnostico_situacional',
        ),
        migrations.RemoveField(
            model_name='proyectorsu',
            name='fundamentacion',
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_asociaciones',
            field=models.BooleanField(default=False, help_text='1.9e Asociaciones'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_asociaciones_detalle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_centros_penitenciarios',
            field=models.BooleanField(default=False, help_text='1.9i Centros Penitenciarios'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_centros_penitenciarios_detalle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_comunidad_universitaria',
            field=models.BooleanField(default=False, help_text='1.9a Comunidad universitaria - interna'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_comunidad_universitaria_detalle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_gobierno_local',
            field=models.BooleanField(default=False, help_text='1.9d Gobierno Local'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_gobierno_local_detalle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_gobierno_nacional',
            field=models.BooleanField(default=False, help_text='1.9d Gobierno Nacional'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_gobierno_nacional_detalle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_gobierno_regional',
            field=models.BooleanField(default=False, help_text='1.9d Gobierno Regional'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_gobierno_regional_detalle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_inst_educativas_basicas',
            field=models.BooleanField(default=False, help_text='1.9b Instituciones Educativas Básico Regulares'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_inst_educativas_basicas_detalle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_inst_educativas_especiales',
            field=models.BooleanField(default=False, help_text='1.9c Instituciones Educativas Especiales'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_inst_educativas_especiales_detalle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_organizaciones_comunales',
            field=models.BooleanField(default=False, help_text='1.9f Organizaciones comunales'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_organizaciones_comunales_detalle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_otro',
            field=models.BooleanField(default=False, help_text='1.9j Otro'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_otro_detalle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_sector_empresarial',
            field=models.BooleanField(default=False, help_text='1.9g Sector empresarial'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_sector_empresarial_detalle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_sectores_laborales',
            field=models.BooleanField(default=False, help_text='1.9h Sectores laborales'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='benef_sectores_laborales_detalle',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='descripcion_gastos',
            field=models.TextField(blank=True, help_text='IX Detalle de los rubros de gasto y su distribución', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='diag_aportes_formacion',
            field=models.TextField(blank=True, help_text='III Aportes desde la formación profesional', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='diag_estado_grupo',
            field=models.TextField(blank=True, help_text='III Estado actual del grupo beneficiario', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='diag_justificacion_intervencion',
            field=models.TextField(blank=True, help_text='III Justificación de la intervención', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='diag_problemas_detectados',
            field=models.TextField(blank=True, help_text='III Problemas detectados', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='eje_rsu_subitems',
            field=models.JSONField(blank=True, default=dict, help_text='1.10 Sub-ítems seleccionados por eje RSU (Gestión, Formación, Investigación, Extensión, Voluntariado)'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='fecha_encuesta_alumnos',
            field=models.DateField(blank=True, help_text='1.17 Encuesta a Estudiantes', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='fecha_encuesta_docentes',
            field=models.DateField(blank=True, help_text='1.17 Encuesta a Docentes', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='fecha_encuesta_grupo_destinatario',
            field=models.DateField(blank=True, help_text='1.17 Encuesta a Grupo Destinatario', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='fecha_evaluacion_avance',
            field=models.DateField(blank=True, help_text='1.15 Fecha de evaluación de avance', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='1.14 Fecha de inicio', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='fecha_termino',
            field=models.DateField(blank=True, help_text='1.16 Fecha de término', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='fuente_financiamiento',
            field=models.CharField(blank=True, choices=[('recursos_propios', 'Recursos propios'), ('fondos_facultad', 'Fondos de Facultad'), ('fondos_universidad', 'Fondos de la Universidad'), ('externo_publico', 'Financiamiento externo público'), ('externo_privado', 'Financiamiento externo privado'), ('mixto', 'Mixto'), ('otro', 'Otro')], help_text='IX Fuente de financiamiento', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='fund_mecanismo_ensenanza',
            field=models.TextField(blank=True, help_text='II ¿Cuál será el mecanismo de enseñanza-aprendizaje?', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='fund_para_que_proyecto',
            field=models.TextField(blank=True, help_text='II ¿Para qué servirá el proyecto?', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='fund_por_que_grupo',
            field=models.TextField(blank=True, help_text='II ¿Por qué se eligió el grupo beneficiario?', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='impacto_esperado',
            field=models.TextField(blank=True, help_text='V Impacto esperado general', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='indicador',
            field=models.CharField(blank=True, help_text='1.13 Indicador propuesto en el plan (ej: N° de docentes capacitados)', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='lugar_ejecucion',
            field=models.CharField(blank=True, help_text='1.18 Lugar de ejecución (ej: Distrito de Cayma, Arequipa)', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='meta_cuantitativa',
            field=models.CharField(blank=True, help_text='1.12 Meta cuantificable (ej: Capacitar a 50 docentes)', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='monto_financiamiento',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='IX Presupuesto estimado total (S/)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='nro_docentes',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='1.7 Nro. de docentes que participaron', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='nro_estudiantes',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='1.8 Nro. de estudiantes universitarios que participaron', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='objetivo_general',
            field=models.TextField(blank=True, help_text='IV Objetivo general del proyecto', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='observaciones_financiamiento',
            field=models.TextField(blank=True, help_text='IX Observaciones adicionales sobre el financiamiento', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='rec_hum_administrativos',
            field=models.PositiveIntegerField(default=0, help_text='VIII Administrativos'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='rec_hum_docentes',
            field=models.PositiveIntegerField(default=0, help_text='VIII Docentes'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='rec_hum_egresados',
            field=models.PositiveIntegerField(default=0, help_text='VIII Egresados'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='rec_hum_estudiantes',
            field=models.PositiveIntegerField(default=0, help_text='VIII Estudiantes'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='rec_hum_otros',
            field=models.PositiveIntegerField(default=0, help_text='VIII Otros recursos humanos'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='rec_hum_voluntarios',
            field=models.PositiveIntegerField(default=0, help_text='VIII Voluntarios'),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='rec_mat_afiches',
            field=models.TextField(blank=True, help_text='VIII Afiches', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='rec_mat_equipos',
            field=models.TextField(blank=True, help_text='VIII Equipos', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='rec_mat_material_didactico',
            field=models.TextField(blank=True, help_text='VIII Material didáctico', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='rec_mat_otros',
            field=models.TextField(blank=True, help_text='VIII Otros materiales', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='rec_mat_utiles',
            field=models.TextField(blank=True, help_text='VIII Útiles', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='resultado_en_beneficiarios',
            field=models.TextField(blank=True, help_text='V Resultados esperados en los beneficiarios', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='resultado_en_curriculo',
            field=models.TextField(blank=True, help_text='V Resultados esperados en el proceso curricular', null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='tipo_actividad',
            field=models.CharField(blank=True, choices=[('programas_formativos', 'Programas formativos'), ('acompanamiento', 'Acompañamiento a sectores identificados'), ('asesoria', 'Asesoría'), ('acercamiento_comunidad', 'Iniciativas de acercamiento a la comunidad'), ('otro', 'Otros')], help_text='1.11 Tipo de actividad', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proyectorsu',
            name='tipo_actividad_otro',
            field=models.CharField(blank=True, help_text="1.11 Descripción si el tipo de actividad es 'Otro'", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='proyectorsu',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código asignado por la comisión OURS una vez consolidados todos los proyectos.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='proyectorsu',
            name='departamento',
            field=models.ForeignKey(help_text='1.3 Departamento Académico', on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='usuarios.departamentoacademico'),
        ),
        migrations.AlterField(
            model_name='proyectorsu',
            name='eje_rsu',
            field=models.ForeignKey(help_text='1.10 Eje RSU principal del proyecto', on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='planificacion.ejersu'),
        ),
        migrations.AlterField(
            model_name='proyectorsu',
            name='escuela',
            field=models.ForeignKey(help_text='1.2 Escuela Profesional', on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='usuarios.escuelaprofesional'),
        ),
        migrations.AlterField(
            model_name='proyectorsu',
            name='facultad',
            field=models.ForeignKey(help_text='1.1 Facultad', on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='usuarios.facultad'),
        ),
        migrations.AlterField(
            model_name='proyectorsu',
            name='semestre_academico',
            field=models.CharField(help_text='1.4 Semestre académico (ej: 2023-A)', max_length=20),
        ),
        migrations.AlterField(
            model_name='proyectorsu',
            name='titulo',
            field=models.CharField(help_text='1.6 Título del proyecto', max_length=400),
        ),
        migrations.CreateModel(
            name='ObjetivoEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Descripción del objetivo específico')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_especificos', to='proyectos.proyectorsu')),
            ],
            options={
                'verbose_name': 'Objetivo Específico',
                'verbose_name_plural': 'Objetivos Específicos',
                'db_table': 'proyecto_objetivos_especificos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CronogramaAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción de la acción', max_length=400)),
                ('mes_semana', models.CharField(blank=True, help_text='Periodo de ejecución (ej: Mes 1, Sem 2)', max_length=100, null=True)),
                ('responsable', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_avance', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('postergado', 'Postergado')], default='pendiente', max_length=30)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronograma', to='proyectos.proyectorsu')),
            ],
            options={
                'verbose_name': 'Acción de Cronograma',
                'verbose_name_plural': 'Acciones de Cronograma',
                'db_table': 'proyecto_cronograma',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='ActividadProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la actividad', max_length=300)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción breve', null=True)),
                ('curso_vinculado', models.CharField(blank=True, help_text='Asignatura vinculada', max_length=300, null=True)),
                ('responsable', models.CharField(blank=True, help_text='Responsable de la actividad', max_length=200, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('evidencia_esperada', models.CharField(blank=True, help_text='Evidencia esperada (ej: Fotos, listas, informes)', max_length=400, null=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='proyectos.proyectorsu')),
            ],
            options={
                'verbose_name': 'Actividad de Proyecto',
                'verbose_name_plural': 'Actividades de Proyecto',
                'db_table': 'proyecto_actividades',
                'ordering': ['orden', 'fecha'],
            },
        ),
    ]
