# Generated by Django 4.2.13 on 2026-06-18 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_tipo_actividad_json_fuente_financiamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectorsu',
            name='benef_asociaciones_detalle',
        ),
        migrations.RemoveField(
            model_name='proyectorsu',
            name='benef_centros_penitenciarios_detalle',
        ),
        migrations.RemoveField(
            model_name='proyectorsu',
            name='benef_comunidad_universitaria_detalle',
        ),
        migrations.RemoveField(
            model_name='proyectorsu',
            name='benef_gobierno_local_detalle',
        ),
        migrations.RemoveField(
            model_name='proyectorsu',
            name='benef_gobierno_nacional_detalle',
        ),
        migrations.RemoveField(
            model_name='proyectorsu',
            name='benef_gobierno_regional_detalle',
        ),
        migrations.RemoveField(
            model_name='proyectorsu',
            name='benef_inst_educativas_basicas_detalle',
        ),
        migrations.RemoveField(
            model_name='proyectorsu',
            name='benef_inst_educativas_especiales_detalle',
        ),
        migrations.RemoveField(
            model_name='proyectorsu',
            name='benef_organizaciones_comunales_detalle',
        ),
        migrations.RemoveField(
            model_name='proyectorsu',
            name='benef_sector_empresarial_detalle',
        ),
        migrations.RemoveField(
            model_name='proyectorsu',
            name='benef_sectores_laborales_detalle',
        ),
        migrations.CreateModel(
            name='DocumentoSustentoProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='proyectos/sustento/')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_sustento', to='proyectos.proyectorsu')),
            ],
            options={
                'verbose_name': 'Documento de Sustento de Proyecto',
                'verbose_name_plural': 'Documentos de Sustento de Proyecto',
                'db_table': 'proyecto_documentos_sustento',
            },
        ),
    ]
