# Generated by Django 4.2.13 on 2026-06-15 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_sesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjeRSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Eje RSU',
                'verbose_name_plural': 'Ejes RSU',
                'db_table': 'ejes_rsu',
            },
        ),
        migrations.CreateModel(
            name='LineaEstrategica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eje_rsu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_estrategicas', to='planificacion.ejersu')),
            ],
            options={
                'verbose_name': 'Línea Estratégica',
                'verbose_name_plural': 'Líneas Estratégicas',
                'db_table': 'lineas_estrategicas',
            },
        ),
        migrations.CreateModel(
            name='MatrizOperativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto_global', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('cerrada', 'Cerrada')], default='borrador', max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrices_coordinadas', to=settings.AUTH_USER_MODEL)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrices', to='usuarios.facultad')),
            ],
            options={
                'verbose_name': 'Matriz Operativa',
                'verbose_name_plural': 'Matrices Operativas',
                'db_table': 'matrices_operativas',
            },
        ),
        migrations.CreateModel(
            name='ODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ODS',
                'verbose_name_plural': 'ODS',
                'db_table': 'ods',
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('anio', models.IntegerField()),
                ('semestre', models.CharField(choices=[('I', 'Semestre I'), ('II', 'Semestre II'), ('Anual', 'Anual')], max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Periodo Académico',
                'verbose_name_plural': 'Periodos Académicos',
                'db_table': 'periodos_academicos',
            },
        ),
        migrations.CreateModel(
            name='ObjetivoInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('resultado_esperado', models.TextField(blank=True, null=True)),
                ('meta_cuantitativa', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eje_rsu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objetivos', to='planificacion.ejersu')),
                ('linea_estrategica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos', to='planificacion.lineaestrategica')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='planificacion.matrizoperativa')),
            ],
            options={
                'verbose_name': 'Objetivo Institucional',
                'verbose_name_plural': 'Objetivos Institucionales',
                'db_table': 'objetivos_institucionales',
            },
        ),
        migrations.AddField(
            model_name='matrizoperativa',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrices', to='planificacion.periodoacademico'),
        ),
        migrations.CreateModel(
            name='IndicadorInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('unidad_medida', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_meta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_alcanzado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metodo_verificacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='planificacion.objetivoinstitucional')),
            ],
            options={
                'verbose_name': 'Indicador Institucional',
                'verbose_name_plural': 'Indicadores Institucionales',
                'db_table': 'indicadores_institucionales',
            },
        ),
        migrations.CreateModel(
            name='ActividadSugerida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('anio_academico', models.IntegerField(blank=True, choices=[(1, '1.er año'), (2, '2.do año'), (3, '3.er año'), (4, '4.to año'), (5, '5.to año')], null=True)),
                ('tipo_actividad', models.CharField(blank=True, max_length=150, null=True)),
                ('destinatarios', models.CharField(blank=True, max_length=300, null=True)),
                ('presupuesto_ref', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('eje_rsu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_sugeridas', to='planificacion.ejersu')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_sugeridas', to='planificacion.matrizoperativa')),
                ('objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_sugeridas', to='planificacion.objetivoinstitucional')),
            ],
            options={
                'verbose_name': 'Actividad Sugerida',
                'verbose_name_plural': 'Actividades Sugeridas',
                'db_table': 'actividades_sugeridas',
            },
        ),
    ]
