# Generated by Django 4.2.13 on 2026-09-12 21:55

import apps.planificacion.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planificacion', '0006_seed_sub_ejes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Nombre del documento', max_length=255)),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripción del contenido')),
                ('categoria', models.CharField(choices=[('linea_investigacion', 'Línea de Investigación'), ('objetivo_regional', 'Objetivo Regional'), ('objetivo_nacional', 'Objetivo Nacional'), ('ods', 'ODS'), ('guia_formulacion', 'Guía de Formulación'), ('normativa', 'Normativa / Directiva'), ('otro', 'Otro')], db_index=True, default='otro', max_length=30)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='planificacion/documentos_apoyo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx']), apps.planificacion.models.validate_documento_apoyo_size])),
                ('enlace_externo', models.URLField(blank=True, help_text='Enlace externo (Drive, etc.) cuando no se adjunta archivo', null=True)),
                ('activo', models.BooleanField(db_index=True, default=True, help_text='Los documentos inactivos dejan de listarse para los docentes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publicado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_apoyo_publicados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Apoyo',
                'verbose_name_plural': 'Documentos de Apoyo',
                'db_table': 'documentos_apoyo',
                'ordering': ['-created_at'],
            },
        ),
    ]
