# Generated by Django 4.2.13 on 2026-09-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0007_documentoapoyo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoNacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Objetivo Nacional',
                'verbose_name_plural': 'Objetivos Nacionales',
                'db_table': 'objetivos_nacionales',
                'ordering': ['codigo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoRegional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Objetivo Regional',
                'verbose_name_plural': 'Objetivos Regionales',
                'db_table': 'objetivos_regionales',
                'ordering': ['codigo', 'nombre'],
            },
        ),
    ]
