# Generated by Django 4.2.13 on 2026-09-17 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0010_matriz_como_documento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentoApoyo',
        ),
    ]
