# Generated by Django 4.2.13 on 2026-10-01 02:07

import apps.planificacion.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0011_borrar_documentoapoyo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matrizoperativa',
            options={'ordering': ['-created_at'], 'verbose_name': 'Documento de apoyo', 'verbose_name_plural': 'Documentos de apoyo'},
        ),
        migrations.AlterField(
            model_name='matrizoperativa',
            name='archivo',
            field=models.FileField(upload_to='planificacion/matriz/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), apps.planificacion.models.validate_documento_size]),
        ),
    ]
